spring.datasource.url=jdbc:postgresql://localhost:5433/ems
spring.datasource.username=postgres
spring.datasource.password=123456
spring.kafka.bootstrap-servers=localhost:19092,localhost:19094,localhost:19096
spring.kafka.consumer.group-id=ems-consumer-group
app.jwt.secret=ems-backend-dev-secret-key-minimum-32-characters-long
app.jwt.expiration-ms=86400000
logging.level.org.springframework.kafka=DEBUG
logging.level.org.springframework.kafka.listener=DEBUG